### ISSUE TITLE
in windows xp the tag display is unnormal in V181129

### ISSUE THREAD

**Issue by cvster** [tablacus/TablacusExplorer#168]
in windows xp the tag display is unnormal in V181129

**Comment by tablacus** [comment]
I have not encountered it.

Please read this and let me know your environment.
[When reporting a problem, please be specific.](https://www.penflip.com/LightTempler/tablacus-explorer/blob/master/when-reporting-a-problem-please-be-specific.txt)

Regards.

**Comment by cvster** [comment]
Hi,

The computer is a virturl machine on VirtualBox, which may cause this problem. I don't use it frequently and if no others encounter it you may ignore. 

I like TE very much. Thank you.

About the environment, I download the 18.12.5 and the pictures are following.


![screenshot_2](https://user-images.githubusercontent.com/26502072/49713565-43500380-fc84-11e8-86c9-f62b77dc74e2.png)
![screenshot_3](https://user-images.githubusercontent.com/26502072/49713566-43500380-fc84-11e8-9d05-ff932910a19c.png)
![screenshot_4](https://user-images.githubusercontent.com/26502072/49713568-43500380-fc84-11e8-9625-81d4466c9016.png)
![screenshot_1](https://user-images.githubusercontent.com/26502072/49713569-43e89a00-fc84-11e8-9d59-f5cffd63ab8a.png)

**Comment by tablacus** [comment]
I think that you are using IE6.
For now, I have adjusted it onTablacus Explorer 18.12.10.
But I already have no IE 6 environment.
Please do not expect too much.

Regards,

**Comment by cvster** [comment]
Yes, it's IE6.
I think it would be ok if update IE.
Thanks.

**Comment by ccfs** [comment]
Gaku,

A few months ago I tried TE on my old Windows XP SP3 with IE6. It almost could not run. Some add-ons got problems. So I installed IE8 and TE ran better. Therefore I think IE8 is a minimum requirement.

If TE is amended to work in a clumsy way just to be compatible with IE6, I don't think this is worthwhile. Besides you cannot guarantee TE and the add-ons to work under IE6 since you do not have such environment.

My suggestion:
- XP users should upgrade to IE8
- No need to amend TE to make it work (?) under IE6

Regards,
