### ISSUE TITLE
Lack of documentation about API and developping add-on

### ISSUE THREAD

**Issue by Moliman** [tablacus/TablacusExplorer#297]
I would like to write some add-ons, but I can't find any documentation. Their is really few detail on JS Object (TreeView, FolderView, ect.) and no info on API function (api.GetDisplayNameOf, api.CreatePopupMenu()) which I probably miss many of them since I can only find them on existing add-on

So far I've found:
- Examples with existing add-on (as a sais earlier), but it don't cover everything
- [This website](https://www.penflip.com/LightTempler/tablacus-explorer), mentionned in README, but it's a dead link.
- [This page](http://www.eonet.ne.jp/~gakana/tablacus/objects/) but it only cover name of each objet, and many of them I couldn't find their data.

**Comment by tablacus** [comment]
I'm sorry. I don't have the time and English skills.

The API function is basically a wrapper that calls the Win32 API of the same name.
CreatePopupMenu is [CreatePopupMenu](https://docs.microsoft.com/ja-jp/windows/win32/api/winuser/nf-winuser-createpopupmenu)
GetDisplayNameOf is [IShellFolder::GetDisplayNameOf](https://docs.microsoft.com/en-us/windows/win32/api/shobjidl_core/nf-shobjidl_core-ishellfolder-getdisplaynameof)

Since JavaScript basically doesn't allow passing by reference, there are parts of it that are changed to return values instead.

Regards,

**Comment by Moliman** [comment]
Alright, thanks the advice. I'll check out. And thanks for this amazing Windows File Explorer. I've started using it three days ago, and it's by far the best I've found.
