### ISSUE TITLE
TE v20.6.27 crashes

### ISSUE THREAD

**Issue by daVe55w** [tablacus/TablacusExplorer#303]
Just upgraded to TE v20.6.27. Upon copying or moving files from one tab to another, TE crashes.

**Comment by tablacus** [comment]
I have not encountered this.

Please read this and let me know your environment.
https://github.com/tablacus/TablacusExplorer/wiki/report-problem

What was the previous version that was updated to v20.6.27?

What file operation add-ons do you use?
(e.g. Multi thread, Multi process, FastCopy, Fire Fast Copy, TeraCopy)

Is the copy or move method drag and drop? Or is it copy and paste? Or is there another way?

If it's drag and drop, is the drop destination on the tab? Or is it on the list?

What happens if you copy from Explorer to Tablacus Explorer or from Tablacus Explorer to Explorer?

Regards,
