### ISSUE TITLE
Make compatible to Wine to have a really nice Explorer

### ISSUE THREAD

**Issue by blackcrack** [tablacus/TablacusExplorer#334]
Hi,

it is a really nice work, i have fellow this project since a couples month.. but the bad is,
in Wine works not really nice, could you maybe make more compatible to works also in wine ?
If it's works in Wine, so should it also works in Reactos ... 

best regards
Blacky

**Comment by tablacus** [comment]
I think the main reason why Tablacus Explorer does not work on Wine is because it uses Trident as its browser engine.
I am currently working on the Tablacus Explorer Blink project, which will replace the browser engine in Tablacus Explorer with Edge (Chrome).
If successful, I believe this will increase the likelihood of it working in Wine.

Regards,

**Comment by blackcrack** [comment]
i am curios and wait if it's usable *drool* :)))

best regards
Blacky
