### ISSUE TITLE
Option / Add-ons / Detail button inactive : Bug on not ?

### ISSUE THREAD

**Issue by Lidgeu** [tablacus/TablacusExplorer#509]
In this dialog, when any of the sort options is selected : 

1. The Up and Down buttons are inactivated : right.
2. But so are all the  "Details" (Détails) buttons ???
![Option-Addon-Detail](https://user-images.githubusercontent.com/88983709/146098580-dd1040c1-718e-49e6-929c-7597fd48731e.jpg)

Why ?
By the way, the sort option selected is not remembered !!! (a second bug?)

**Comment by Lidgeu** [comment]
Problem solve ... almost. ;o)
Details are displayed whatever the sort option. However, their existing French translations are ignored.
![Option-Addon-Detail-TE211215](https://user-images.githubusercontent.com/88983709/146283861-536abb30-b14a-4928-b886-fa1900ef31fd.jpg)

**Comment by ccfs** [comment]
If your language file is named "fr.xml" or "fr_something.xml", TE will show the add-on name and description from the `<fr>` part of "config.xml". Otherwise TE will translate them according to the content of the language file. I think the above is the latter. Since there is no line for the description, the add-on name is translated but the description is not.

Regards,

**Comment by Lidgeu** [comment]
See #466.

Solved. I close the issue ;o)
