### ISSUE TITLE
Option to trigger Addons Update Plugin manually

### ISSUE THREAD

**Issue by kettenfett** [tablacus/TablacusExplorer#559]
Hello,

It would be great to be able to trigger the "Add-on updater" addon manually.

It would be helpful, because I'm still getting #539 , so I keep having to update Tablacus by overwriting the folder with the new files, but this doesn't update the addons.

**Comment by ccfs** [comment]
Use a menu option or a tool bar button with:
```
Type = Add-ons
Options = Addons updater
```
Example:
![image](https://user-images.githubusercontent.com/34089121/153553514-d1d7998c-338d-4309-961a-df68ed241d4e.png)

I think the #539 problem is caused by a broken association at your computer. See these:
https://www.inflectra.com/support/knowledgebase/kb58.aspx
https://www.winhelponline.com/blog/error-there-is-no-script-engine-for-file-extension-when-running-js-files/

**Comment by kettenfett** [comment]
It worked.
I just had to enter `assoc .js=JSFile` into an elevated command prompt.

Thx for providing the solution.
