### ISSUE TITLE
Feature request - FolderPicture

### ISSUE THREAD

**Issue by 921j** [tablacus/TablacusExplorer#685]
Because in daily work, I often process a lot of video files, so I prefer the function of the FolderPicture(WLX PlugIn) of Total Commander. The intuitive display is like the effect of the ICO file but it is not as troublesome as ICO. Although I know that Tablacus is compatible with Addon compatible with the Total Commander WLX plug -in, I have not been able to achieve it. I wonder if Tablacus can do it?

FolderPicture with Total commander:
![2023-09-23_002252](https://github.com/tablacus/TablacusExplorer/assets/29940386/03bdf130-6df3-4b44-888e-0f735c2be6bb)

XYplorer default ( video also can display ):
![2023-09-23_002448](https://github.com/tablacus/TablacusExplorer/assets/29940386/69d034d2-f97d-438a-bf67-eeeca0f76a4a)

Tablacus:
![2023-09-23_002339](https://github.com/tablacus/TablacusExplorer/assets/29940386/98e74013-bac0-4252-9b50-9776dcc3dddb)

If possible, I hope that tablacus can integrate the two. It can not only use the Folder.png in the folder as a picture with a folder recognition border, but also support the display of Folder1.png and Folder2.png in the thumbnails.

**Comment by 921j** [comment]
I use the Addon "Folder Image", sometimes it works,but most of the time not, and the driver icon becomes the following：
![2023-09-23_125415](https://github.com/tablacus/TablacusExplorer/assets/29940386/78c7646d-c19d-4cd4-b276-1910cdbd781c)

**Comment by ccfs** [comment]
From where can I download FolderPiction WLX Plug-in?

**Comment by 921j** [comment]
> FolderPicture

Sorry It's a misspelling，shoud be FolderPicture:
[http://totalcmd.net/plugring/folderpicture.html](url)

**Comment by ccfs** [comment]
You have to use 2 add-ons:
1. "Thumbnail plus": It changes medium and larger icons to thumbnails for selected types. TICK "Folder".
2. "Folder image": It produces folder thumbnails for "Thumbnail plus" using the FIRST IMAGE file in a folder.
	- You can specify a "Filter" to limit the file names/types (e.g. folder*.png) in the search for an image file.
	- Unfortunately it CANNOT do VIDEO files. The picture you show above is not produced by TE but by Windows.

See the [PDF](https://github.com/ccfs/TablacusExplorer/issues/1) for more details.

**Comment by 921j** [comment]
1. When Checking "Folder" in "Thumbnail plus", the Drive's icon changed, but I only want Folder display an named "Folder.jpg" or "Folder.png" in it as it's thumbnail; and "Thumbnail plus" only works on the drive and the root directory， can't working with sub-folder;
 
![2023-09-25_222408](https://github.com/tablacus/TablacusExplorer/assets/29940386/60952cef-bc0e-45eb-a78d-339454f3ca51)

2. "Folder image" only a little effect，and only support jpg

![2023-09-25_224823](https://github.com/tablacus/TablacusExplorer/assets/29940386/47da43e1-6c56-41a2-af44-6195c37ebd96) ![2023-09-25_224839](https://github.com/tablacus/TablacusExplorer/assets/29940386/8fb77d54-9d8d-4267-8bc9-35a9a20b8122)

![2023-09-25_224859](https://github.com/tablacus/TablacusExplorer/assets/29940386/6e5226ba-aa53-4897-87ce-dbf6d1823da9) ![2023-09-25_224910](https://github.com/tablacus/TablacusExplorer/assets/29940386/28234308-b6c3-47e8-ba72-e1f86b53ab09)

![2023-09-25_224928](https://github.com/tablacus/TablacusExplorer/assets/29940386/761a605e-6355-4b57-a677-e98cc512b9f2) ![2023-09-25_224939](https://github.com/tablacus/TablacusExplorer/assets/29940386/2b2e6d53-d9ec-42d6-8279-e65ec9f4a5a8)

and I just want this
![2023-09-25_224859](https://github.com/tablacus/TablacusExplorer/assets/29940386/6e5226ba-aa53-4897-87ce-dbf6d1823da9) https://user-images.githubusercontent.com/29940386/269998239-69d034d2-f97d-438a-bf67-eeeca0f76a4a.png

**Comment by ccfs** [comment]
No, your conclusions are wrong. "Thumbnail plus" does not need "desktop.ini". From the pictures you posted above, "Folder image" was NOT working, because the thumbnail would not have any border.

Please configure the add-ons as follows:

**Thumbnail plus**
Folder: ticked
Priority: *
![image](https://github.com/tablacus/TablacusExplorer/assets/34089121/0f16f8d2-27a3-4fc7-b17f-fdb507dd413e)

**Folder image**
all defaults
![image](https://github.com/tablacus/TablacusExplorer/assets/34089121/45cfc7d6-9dcd-4d34-8efa-47be60b008ed)

Please disable "Total Commander Lister Plug-in" add-on too. 

If you still cannot see the thumbnails, it may be due some other reasons. Please choose "Help > About", click "Copy" button and paste the TE info in your reply.

**Comment by 921j** [comment]
I checked again and found that if these two items of "thumbnail engine" are checked, desktop.ini is not needed.

![2023-09-26_203748](https://github.com/tablacus/TablacusExplorer/assets/29940386/91fc2cee-878d-4bca-a898-af17665e443b)

I don't know if unchecking these two items will have any side effect?


I mean, Could Tablacus also add a yellow border style to the image of the folder like Xyplorer does? This makes it easier to distinguish between folders or video files.

![1](https://github.com/tablacus/TablacusExplorer/assets/29940386/cbf7e569-344e-4b25-bb64-df254d05abee)

![2](https://github.com/tablacus/TablacusExplorer/assets/29940386/62c8db04-cb94-4453-a462-885ea281155b)

**Comment by ccfs** [comment]
You should uninstall "Thumbnail engine" and setup "Thumbnail plus" & "Folder image" as stated above.

"Thumbnail engine" generates video and folder thumbnails in the same way as Windows. "Folder image" generates folder thumbnails using the first image file in a folder. Since you have enabled both, the former one overrides the latter one. Therefore you have never got "Folder image" working.

This is what you will get:
![folderimage noicon](https://github.com/tablacus/TablacusExplorer/assets/34089121/97945456-090a-42c4-9fe8-a40579fc64d5)

You can opt for "Icon" in "Thumbnail plus" so that you can see the item types. TE does not provide any border option.
![folderimage icon](https://github.com/tablacus/TablacusExplorer/assets/34089121/9b19a8f1-4a13-4c94-9220-2a191a95fdae)

Alternatively, you can enable "Show frames" or use "Preview" add-on to see the types.
![image](https://github.com/tablacus/TablacusExplorer/assets/34089121/965aec30-d446-415f-b62e-9a3cbf314623)

**Comment by 921j** [comment]
Thanks!
