### ISSUE TITLE
Opening TE by clicking folder on the desktop opens three additional "dead" tabs

### ISSUE THREAD

**Issue by PLUPPERT** [tablacus/TablacusExplorer#707]
I haven't found any other reports about this bug, but please tell me if there are.

I'm otherwise very pleased with TE and this is not a big thing, but it is oh so annoying.

As the title suggests there is three additional "dead" folder tabs opened appart from the desired folder when i start TE by clicking a folder on my desktop.
There is no problem when navigating to Desktop from within TE.

I've tried activating and deactivating several add-ons, looking in their respective settings and spent hours googleing for a solution, but no luck so far.

Is there a solution or does anyone have an idea of what to do/look for?

(I'm using Windows 11)

![tablacus](https://github.com/tablacus/TablacusExplorer/assets/85617763/88087cf2-422d-4e8e-8f9c-4097f8d4cf31)

**Comment by ccfs** [comment]
Actually how do you start TE? Normally you cannot start TE by clicking a FOLDER.

1. Is your "folder" a shortcut (.lnk file) to run TE with a folder path? If so, please show me the "Properties" of the shortcut file.

2. Have you set up the Registry so that TE starts when you click a folder? If so, please show me the Registry entries.

3. Do you use "Shell execution hook" add-on (not likely since the add-on probably cannot run on Windows 11)?

4. Do you use "Open instead" add-on?

Please choose Help > About TE, copy your TE info, and paste it to your reply.

**Comment by PLUPPERT** [comment]
Your questions actually made me stumble over the cause of my problem.
For some reason my Registry entries looked like this:
"C:\ProgramData\chocolatey\lib\tablacus\tools\TE64.EXE" "%1" /T /O /S

Causing the three additional tabs to be added because of "/T /O /S"  when TE where opened (with the help of add-ons "Shell execution hook" and "Open instead") by clicking a folder on my desktop.
Now that "/T /O /S" have been removed TE works like a charm!

I apologise for my noobiness.
I will close this issue.

Thank you so very much for your support in my selfinflicted issue and for a great file explorer!

Best regards,
Pluppert

**Comment by JokeDeity** [comment]
I'm so grateful for this thread, spent hours trying to figure it out, I also had /O in my reg, now it's all fixed up!
