### ISSUE TITLE
Feature Request: More Options/Limitations for Multiple Executions

### ISSUE THREAD

**Issue by Ichisich** [tablacus/TablacusExplorer#732]
I tried the add-on "Multiple Executions", and it does what I want.
Letting me drag a tab outside the current window and open it in a new instance of Tablacus.
But the drawback is that now every folder I open, via link, shortcut or the start menu is also sent to a new instance instead of a simple tab.

Would be neat if there is an option, so multiple executions only generates a new instance when explicitly triggered.

**Comment by ccfs** [comment]
Are these what you want?

Run "TE64.EXE" when TE is already running -> go to existing window
Run "TE64.EXE c:\" when TE is already running -> open c:\ in existing window
Run "TE64.EXE /new" when TE is already running -> new window
Run "TE64.EXE /new c:\" when TE is already running -> open c:\ in NEW window
Drag a tab outside current window -> new window

**Comment by Ichisich** [comment]
Sounds about right.
Only thing I would add is the possibility to open a new instance by middle mouse clicking the tablacus tasbar button.

**Comment by ccfs** [comment]
Let's assume that you have ticked "Always" on the Options page of the add-on.

Then you will get a new window when you run TE by:
- left-click a desktop shortcut to TE
- left-click a start menu item of TE
- left-click or middle-click task bar icon of TE

All 3 cases above are actually .LNK to TE, which may also include a folder path to open.

Questions:
1. Exactly under which situation you do NOT want a new window? All cases above are all explicitly triggered by you.
2. Have you ever set up any Registry entries so that TE runs when you click a shortcut to a FOLDER?

**Comment by Ichisich** [comment]
"Always" is of course ticked off.

> Questions:
> 
>     1. Exactly under which situation you do NOT want a new window? All cases above are all explicitly triggered by you.
Basically always, except when dragging a tab outside the current window or giving an explicit "open in new window" command.


>     2. Have you ever set up any Registry entries so that TE runs when you click a shortcut to a FOLDER?
I set up Tablacus as the default file explorer `HKEY_CLASSES_ROOT\Directory\shell\open\command` and open folders mostly by shortcuts (CTRL+ALT+Key) or windows search.

**Comment by ccfs** [comment]
Currently the add-on checks the command line option to decide whether to open a new window:

|CURRENT|Always = OFF|Always = ON|
|-|-|-|
|Run TE without command line option (Simple start)|Go to current window|New window|
|Run TE with command line option (Open a folder)|New window|New window|
|Drag a tab outside TE|New window|New window|
|Open in new window command|New window|New window|

And these are what you want:

|REQUESTED||
|-|-|
|Run TE without command line option (Simple start)|New window|
|Run TE with command line option (Open a folder)|Go to current window|
|Drag a tab outside TE|New window|
|Open in new window command|New window|

Correct?

**Comment by Ichisich** [comment]
Not sure about 1.
"Run TE without command line option" should probably still go to current window, except when "always" is ticked on.
Starting Tablacus with middle mouse click should go to new window. (Windows convention)
But that's probably beyond the scope of an add-on.

**Comment by ccfs** [comment]
"Starting Tablacus with middle mouse click" is a case of situation 1 ("Clicking TE64.EXE" is also a case of situation 1), and is within the scope of the add-on.
I will try to add an option independent of the "Always" check box to handle your request.

**Comment by ccfs** [comment]
The [patched version](https://github.com/tablacus/TablacusExplorer/issues/692) of TE has been enhanced for your request. Please make sure your TE version is 23.9.13 before you install the patch.

On Options page of the add-on:
1. Choose "Always" for "Run TE" so that middle-clicking TE task bar icon will open a new window.
2. Choose "/nw" for "Run TE with a command line option" so that clicking a shortcut to a folder will open the folder in current window.

**Comment by Ichisich** [comment]
Much appreciated.
